[package]
name = "nami3"
version = "0.1.0"
edition = "2024"
license = "LGPL-3.0"

[dependencies]
clap = { version = "4.5.56", features = ["derive"] }
mp3lame-encoder = "0.2.1"
hound = "3.5.1"
anyhow = "1.0"
